### ISSUE TITLE
E1047: Syntax error in import

### ISSUE THREAD

**Issue by rcrx** [monkoose/vim9-stargate#12]
This plugin will not function for me. I'm receiving this error upon pressing <leader>f:

```
Error detected while processing ~/.vim/autoload/stargate.vim:
E1047: Syntax error in import: '../import/stargate/workstation.vim' as ws  
E117: Unknown function: stargate#OKvim
```
I'm using vim 8.2

**Comment by monkoose** [comment]
Seems like some vim change or bug to vim9 in later versions. Because for me it works on my work machine, but doesn't on my home machine (which has vim 9.0.0813 version).

Will look for it later (because can't trace the error (vim's error doesn't help) currently). Sorry for such inconvenience. Do not use it until i inform you here.

**Comment by monkoose** [comment]
I have pushed some fix to my error. Can you test if it helps to yours? Because none of known by me users of this plugin has the same issue as you, so if it doesn't help, then you should provide more info to trace the bug or it is some issue with your config.

**Comment by monkoose** [comment]
Closed for inactive.

**Comment by rcrx** [comment]
@monkoose I've tested and confirm that I still receive the same error.

**Comment by monkoose** [comment]
I suggest you to update your vim if it is possible and you still using 8.2 version, there was a lot of changes/fixes during vim9 development. But from my side, I should bump required vim version to 9.0+.
